### ISSUE TITLE
Add BunsenLabs icons?

### ISSUE THREAD

**Issue by capn-damo** [BunsenLabs/bunsen-faenza-icon-theme#1]
Suggest adding BL icons, along the lines of https://github.com/BunsenLabs/bunsen-images/blob/master/icon-avatar/Bunsenlabs-flame-256.svg

Both dark and light versions? 

They could be used by any gui dialog utilities written for BunsenLabs.

**Comment by johnraff** [comment]
You mean a "BunsenLabs" icon that can represent the system in various dialogues, menus etc? Sounds like a good idea. 

How many sizes do you have in mind, and what subsection of the theme?

**Comment by capn-damo** [comment]
I would envisage having them in `extras`, with all the usual sizes (although I'll have to investigate how iconpaths are decided by an application)

**Comment by capn-damo** [comment]
An easy workaround for icons for dialogs is to have an svg in `/usr/share/pixmaps`, and just display it with `--window-icon="/usr/share/pixmaps/Bunsenlabs-flame-256.svg"` in the script. This shows the icon in the window titlebar and tint2 taskbar. 
Another advantage of this is that the same image can be displayed within the dialog, without having to ship another one: `--image=/usr/share/pixmaps/Bunsenlabs-flame-256.svg"`

A dark flame on a light background (or vice versa) will ensure it displays in any theme.

**Comment by johnraff** [comment]
There's an icon-avatar section in **bunsen-images-extra** that I think should have gone in the regular **bunsen-images** along with svg as we agreed in May! https://github.com/BunsenLabs/bunsen-images/issues/4#issuecomment-101477811 I overlooked it at the time but those two directories could be moved now - it would mean version bumps and some "breaks" & "replaces" dependencies. We're still at the "RC" phase so I guess this is acceptable.

Both icon-avatar and svg folders go in usr/share/bunsen/bunsen-images atm but 

> have an svg in /usr/share/pixmaps, and just display it with --window-icon="/usr/share/pixmaps/Bunsenlabs-flame-256.svg" in the script.

this basic idea sounds reasonable. 

SVG support is "optional" accoding to freedesktop: http://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html but because it's scaleable it makes things easier in other ways I guess.

Should your Bunsenlabs-flame-256.svg be moved from icon-avatar to svg perhaps?

**Comment by capn-damo** [comment]
IIRC `icon-avatar` was just a place to put oddments at the time, that's why I put `Bunsenlabs-flame-256.svg` there until it was decided what to do. I've done a version with a light background, so it shows up anywhere. I'll move it to svg later, OK?

**Comment by johnraff** [comment]
Sure. I wasn't too involved in those decisions to be honest. svg is for all svg files, regardless of purpose?

**Comment by johnraff** [comment]
OTOH maybe we should just put them all in icon-avatar?

**Comment by capn-damo** [comment]
Or just call it `icons`, and have all icon-type images there, including svg's which would be suitable as icons/avatars. Some of the svg's are large images, and can stay where they are in `svg`.

BTW I've pushed `Bunsenlabs-flame-256.svg` to `svg`

**Comment by johnraff** [comment]
ditributor-logo, distributor-logo-bunsenlabs and start-here icons were added in 2016: https://github.com/BunsenLabs/bunsen-faenza-icon-theme/commit/04ddb7c10e6d5ac160fd4242f366d8e21473b4f0
